### ISSUE TITLE
Bug with registration page (attempting to register a new account ends with an error message)

### ISSUE THREAD

**Issue by huckleberrypie** [opensource-socialnetwork/opensource-socialnetwork#463]
Hmm, 'tis 'swell that the timeline issue has been fixed, but I'm afraid there's this bug to which you guys need to address. For some reason, upon trying to register for a new account, I get a rather generic "Reload this page and then try again" error message - the real kicker here is that the gender/sex radio buttons go red when I click on Create Account.

**Comment by lianglee** [comment]
Send me your website link on arsalan[at]buddyexpress.net

**Comment by huckleberrypie** [comment]
Tried sending you a link to my site but your email address seems to be invalid or something.

**Comment by lianglee** [comment]
You can try to send again, its was dns issue which is solved now,

Gender issue is solved now

**Comment by huckleberrypie** [comment]
Which action file are you referring to?

**Comment by lianglee** [comment]
Please see referenced commits

**Comment by huckleberrypie** [comment]
Alright, my only problem is that I used redirects on my .htaccess file so that the old URL I was using would redirect to the new one. The kicker here is that even if I delete the offending lines on .htaccess the redirect still persists, and that's even when I clear the browser cache!

**Comment by lianglee** [comment]
send us your website link on http://www.informatikon.com/contact

**Comment by huckleberrypie** [comment]
There, just sent you the link to my site.

**Comment by huckleberrypie** [comment]
The SQL fix did the trick on my site, thanks! :D

**Comment by lianglee** [comment]
That is why we always said not to use any development release.

**Comment by huckleberrypie** [comment]
I know. It ain't stable yet but I felt like being in the bleeding edge. 'Sides, it's a small site anyway, and it isn't that critical.

**Comment by lianglee** [comment]
Did you tested speed with Ossn v3.0-dev with cache enabled? I think its much better then 2.3

**Comment by huckleberrypie** [comment]
Haven't enabled the cache yet, but from what I can observe, there's at least some speed improvements with 3.0-dev compared to 2.3.

**Comment by Ramzu** [comment]
hi. i am using version 2.3. can you please tell me how to redirect to absolute url? most users cant register. thanks

**Comment by lianglee** [comment]
@Ramzu, you can try to download redirect_www component for 2.x versions.

**Comment by Ramzu** [comment]
@lianglee,    Wow! Fast response. Thanks a lot! Can I find that in the Components part of the community site?

**Comment by Ramzu** [comment]
@lianglee I found it! thanks
